###
POST http://{{address}}/update/gauge/metric_name/1.1
Content-Type: text/plain

{}


###
POST http://{{address}}/update/counter/metric_name/1
Content-Type: text/plain

{}


### 404
POST http://{{address}}/update/gauge/
Content-Type: text/plain

{}


###
POST http://{{address}}/update/unknown/testCounter/100

{}


###
GET http://{{address}}/value/gauge/testUnknown133


###
GET http://{{address}}/value/counter/metric_name


###
POST http://{{address}}/update/
Content-Type: application/json

{
  "id": "test",
  "type": "counter",
  "delta": 544041449
}


###
POST http://{{address}}/value
Content-Type: application/json

{
  "id": "test",
  "type": "counter"
}


###
GET http://{{address}}/
Accept: html/text
Accept-Encoding: gzip


###
GET http://{{address}}/
Accept: text/plain
Accept-Encoding: gzip


###
POST http://{{address}}/updates/
Content-Type: application/json

[
  {
    "id": "test",
    "type": "counter",
    "delta": 360608547
  },
  {
    "id": "test",
    "type": "counter",
    "delta": 544041449
  }
]
